# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.define :vm1 do |vm1|
    vm1.vm.box = "ubuntu/focal64"
    vm1.vm.network "private_network", ip: "192.168.33.21"
    vm1.vm.provider "virtualbox" do |vb|
      vb.name = "vm1"
      vb.cpus = "2"
      vb.memory = "1024"
    end
  end

  config.vm.define :vm2 do |vm2|
    vm2.vm.box = "ubuntu/focal64"
    vm2.vm.network "private_network", ip: "192.168.33.22"
    vm2.vm.provider "virtualbox" do |vb|
      vb.name = "vm2"
      vb.cpus = "2"
      vb.memory = "1024"
    end
  end

  config.vm.synced_folder '.', '/vagrant', disabled: true
  config.ssh.insert_key = false
end
